### ISSUE TITLE
Update from 0.7.5 to 0.8 causes pymongo.errors.OperationFailure

### ISSUE THREAD

**Issue by trein** [MongoEngine/flask-mongoengine#263] opened 2016-10-03 12:09 UTC
I just updated `flask-mongoengine` from 0.7.5 to 0.8 and started getting the following error:

```
pymongo.errors.OperationFailure: not authorized on XXX to execute command { createIndexes: "user", indexes: [ { sparse: false, key: { username: 1 }, name: "username_1", dropDups: false, background: false, unique: true } ] }
```

I assume something changed related to the order authentication is done while creating a connections.

**Comment by lafrech** [comment] 2016-10-03 16:57
Thanks for reporting.

Closing this as duplicate of https://github.com/MongoEngine/flask-mongoengine/issues/259. Please reopen if needed.

**Closed by lafrech** 2016-10-03 16:57 UTC

**Comment by trein** [comment] 2016-10-03 17:33
Thanks. Sorry for not searching further.
