### ISSUE TITLE
Next Milestone Questions & Call for Maintainers!

### ISSUE THREAD

**Issue by rozza** [MongoEngine/flask-mongoengine#71] opened 2013-10-22 08:38 UTC
@anemitz & @thomasst do you guys have any plans for the next milestone / release of flask-mongoengine?

Unfortunately, I dont have the time available at the minute to fix the issues and push a release.  If you are in the same boat, I'm happy to try and draft in more maintainers!

Any potential maintainers - please post here if you want to help further flask-mongoengine - I'm happy to mentor as well!

**Comment by lafrech** [comment] 2016-02-08 13:53
I'm not sure how much time I'll be able to spend on MongoEngine / flask-mongoengine, but since we plan to use it in an important project, we'll be relying on it, so I'd be glad to help.

For a start, I can do a bit of bugtracker sorting and cleanup. I'm pretty sure a lot of open bugs can be closed.

Also, I just sent two minor PR and, obviously, I'd be happy to see them released in a 0.7.6.

Who's still in there? @losintikfos? @itsnauman? @tyrannosaurus? @csabaszilveszter? @rozza? @anemitz? @thomasst?

Who decides the roadmap? Where?

**Comment by losintikfos** [comment] 2016-02-08 14:12
@lafrech - your contributions are welcomed indeed and also appreciated. We will surely make a collective bundle of minor and major fixes to go in 0.7.6. Currently focus will be on changes/fixes to;
- ensure forward and backward compatibility with new versions of MongoEngine and Flask, 
- ensure new feature in MongoEngine, Flask and WTForms are supported
- keep supporting the project for major release and also
- close most of the bugs raised.

**Comment by lafrech** [comment] 2016-02-08 14:56
As I said, I can help with the bugtracker cleanup. I suggest 

- closing issues that are obviously fixed (linked to merged PR for instance)
- closing as can't reproduce those that are too vague, inviting the OP to reopen if issue still present, giving more details
- adding `can't reproduce` label (or is this what `invalid` is for?), and something like `awaiting answer` or `on hold` to signal the OP was asked for details / retest

Regarding 0.7.6, how shall we proceed? I see 0.7.6 milestone was created. Do you want to open a bug for each of the items you can think of that would go in 0.7.6 and then we release when all of these are closed (or postponed to later milestone)?

Shall we dig into the changelogs for [MongoEngine](https://github.com/MongoEngine/mongoengine/blob/master/docs/changelog.rst), [Flask](https://github.com/mitsuhiko/flask/blob/master/CHANGES) and [WTForms](https://github.com/wtforms/wtforms/blob/master/CHANGES.rst) and spot what needs work here or do you already have this covered?

**Comment by losintikfos** [comment] 2016-02-08 15:09
@lafrech :+1:  for your plan and suggestions to clean-up existing issues.

Regarding `0.7.6` ;

> Do you want to open a bug for each of the items you can think of that would go in 0.7.6 and then we release when all of these are closed (or postponed to later milestone)?

`Yes` - this will enable us cover major user reported issues and suggestions that are candidate to `0.7.6` release.

> Shall we dig into the changelogs for MongoEngine, Flask and WTForms and spot what needs work here or do you already have this covered?

`Yes`  - again I think using both approach will enable us cover various features and fixes required for candidate `0.7.6` release.

What do you think?

**Comment by lafrech** [comment] 2016-02-08 15:40
Actually, I'd rather release a 0.7.6 with what we currently have (that is my 2 PR and maybe the other opened one that passes tests if you validate them, and maybe any bug that would be easily fixed while we are at it).

Wouldn't it be better to use 0.7.x (maintenance versions) for bugfixes and 0.8 (minor versions) as next milestone, so that we don't have to postpone all bugs affected to next milestone each time we want to release a bugfix release and the milestone is not ready?

**Comment by losintikfos** [comment] 2016-02-08 17:37
Not a bad idea at all - #98 feature request is suppose to come with it - pretty tied up at the moment, soon as I am done will get all moved into `0.7.6`.

**Comment by lafrech** [comment] 2016-02-08 20:33
More on the versioning. I like the [Semantic Versioning](http://semver.org/) approach:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>  - MAJOR version when you make incompatible API changes,
>  - MINOR version when you add functionality in a backwards-compatible manner, and
>  - PATCH version when you make backwards-compatible bug fixes.

You seem to agree with this, so let's go for it.

In this case, https://github.com/MongoEngine/flask-mongoengine/issues/98 is clearly `0.8`. Such an enhancement should not block bugfix releases. In practice I don't mind waiting, especially if you expect to be done with it soon, so don't bother and do what is the most simple for you.

**Comment by lafrech** [comment] 2016-02-18 22:12
Regarding bugtracker cleanup, I can't do anything without any privileged access to the repo. AFAIU, I don't need to be a [member of the organization](https://help.github.com/articles/permission-levels-for-an-organization/), but I must be at least an [external collaborator](https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/) with write access to the repo.

**Comment by lafrech** [comment] 2016-02-22 08:42
I was added to team MongoEngine, but I still don't have write access to the repo (and the bugtracker), as flask-mongoengine is not owned by the team (not sure why).

**Comment by rozza** [comment] 2016-02-22 14:39
@lafrech you should be good now

**Comment by lafrech** [comment] 2016-02-22 14:46
Indeed. Thanks @rozza.

**Comment by losintikfos** [comment] 2016-02-24 10:05
[#flask-mongoengine IRC channel](http://webchat.freenode.net/?channels=flask-mongoengine) is available - I will update the README to make this known.

**Comment by losintikfos** [comment] 2016-02-24 11:17
Hi Guys - we looking to dropping support for `MongoEngine` 0.7 in the next major release of `Flask-MongoEngine`.  I think this will enable us enhance `Flask-MongoEngine` an also support features which are possible for later versions of Flask, WTForms and MongoEngine.

@rozza do you have any rejections or suggestion that might be essential to this decision?
@lafrech what do you think?

**Comment by lafrech** [comment] 2016-02-24 11:21
I don't see any reason to keep support for old versions, unless some important distro still ships it in its stable version. But the odds are if someone uses flask-mongoengine (from pip), he's probably using latest ME from pip, not ME07 from distro. (Debian still ships ME06...)

No big deal keeping ME07 support if someone needs it, but otherwise, I don't see any reason to do so.

**Comment by lafrech** [comment] 2016-02-25 08:29
Likewise, I've been wondering about Python 2.6 support. Not that there's an urgent need to drop it, but ultimately, we will. Even Debian oldstable ships 2.7...

From https://github.com/rg3/youtube-dl/issues/5697:

> it is probably reasonable to support python 2.6 while RHEL6 and CentOS6 do (namely 2024 and November 30th, 2020 correspondingly)

2024 ! D'oh !

**Comment by lafrech** [comment] 2016-03-03 10:51
@losintikfos, it looks like we're close to 0.8.

[Issues](https://github.com/MongoEngine/flask-mongoengine/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.8)
[PR](https://github.com/MongoEngine/flask-mongoengine/pulls?q=is%3Aopen+is%3Apr+milestone%3A0.8)

Not sure when I'll get the time, but it could be worth updating the doc before releasing. Add a mention about which versions of ME, pymongo and Python are supported (easy). And maybe document some obscure features that are hidden in the code (longer). If it is too much trouble, let's not hold the release for this, it won't be too late to add that later on.

**Comment by losintikfos** [comment] 2016-03-03 12:39
@lafrech, are you able to update the changelog with your recent changes if relevant? It will help when we are ready to update the doc. I noted on the channel that I've got the connection handler extended and will merge when I've got its test coverage sorted.

When all done - I will look into amending the docs to reflect the changes relevant to 0.8 release.
Thanks

**Comment by lafrech** [comment] 2016-03-03 13:31
> @lafrech, are you able to update the changelog with your recent changes if relevant?

Nothing important, really. Code cleanup. I don't think override_json_encoder rename is worth mentioning.

The TextArea stuff could be mentioned, but I think it makes much more sense to document the whole field_args feature in the docs, maybe with the details of which parameters are accepted (textarea, radio,...). Currently, this can only be found in the code.

> I noted on the channel that I've got the connection handler extended and will merge when I've got its test coverage sorted.

Great!

In the docs, we may also mention that BinaryField is not really supported (https://github.com/MongoEngine/flask-mongoengine/issues/52, https://github.com/MongoEngine/flask-mongoengine/issues/46). It is supported through a TextArea, while one would expect some sort of file uploader (which is complicated to accomplish).

**Comment by brunobelarmino** [comment] 2016-03-04 20:58
Hey team,

I'm using flask-mongoengine in an important project like @lafrech. So i intend to help keep it active.
I can solve some issues and maybe open more ones. :grimacing:
Sounds good for you?

Let me know if you have any other ideas.

**Comment by lafrech** [comment] 2016-03-09 11:27
@losintikfos, @rozza, I don't think I can add @brunobelarmino to the organization/team myself.

I'm not sure I'll implement https://github.com/MongoEngine/flask-mongoengine/issues/214 (HTML5 widgets) any soon. If unsure about https://github.com/MongoEngine/flask-mongoengine/pull/216 (max_length input attribute) and since both are somehow related, we can postpone both to 0.9 and ship 0.8 when done with https://github.com/MongoEngine/flask-mongoengine/issues/98 (new connection handler David is working on) (release early, release often).

**Comment by losintikfos** [comment] 2016-03-09 11:53
@lafrech lets postpone #214 and #216 to `0.8`. I will finalise the connection handler and update the `docs.` as required for release. Connection handler changes is 98% complete including test coverage. You can walk-through (see the link) and perhaps let me know if you have any opinions about it. [See __init__.py, connection.py](https://github.com/losintikfos/flask-mongoengine/tree/bd-dev/flask_mongoengine) and also test coverage [__init__.py, test_connection.py](https://github.com/losintikfos/flask-mongoengine/tree/bd-dev/tests).

### What is outstanding?
- Extend test connection to cover test for when mongodb is not installed but `TESTING` and `TEMP_DB` are enabled.
- Dynamically direct all modules currently monkey patched from ME into F-ME to use F-ME's `connection.py`.
- Update `changelog` and `docs.`.

**Comment by lafrech** [comment] 2016-03-09 14:08
> lets postpone #214 and #216 to 0.9.

Scheduled: https://github.com/MongoEngine/flask-mongoengine/milestones/0.9

Thanks for the feedback on the connection handler. I won't be of help in the coming days, I'm afraid.

**Comment by lafrech** [comment] 2016-05-30 13:54
Flask 0.11 just got released and prints warnings when used with latest (0.7.5) flask-mongoengine. Releasing 0.8 will fix this thanks to https://github.com/MongoEngine/flask-mongoengine/commit/1327e7375f6ff855a72451c862d01ee8ffb289ba.

**Comment by losintikfos** [comment] 2016-06-29 20:34
@lafrech lets grab a chat at IRC if you slightly free.

Ta!

**Comment by lafrech** [comment] 2016-06-30 08:26
@losintikfos I checked out your fix and it works on my app. Thx. I also integrated my doc updates.

**Comment by lafrech** [comment] 2016-08-25 07:54
Now that 0.8 is out, we're getting a little feedback. I created a 0.8.1 milestone (https://github.com/MongoEngine/flask-mongoengine/milestone/7) for the next bugfix release.

**Comment by lafrech** [comment] 2016-10-10 07:51
We get bug reports related to the connexion rework: 0.8 introduced an important regression that triggers a few blocking issues.

I don't have time to dedicate to this right now and apparently neither does @losintikfos. I'm using 0.7.5 in production (internal website) and I think @losintikfos uses 0.8 without issue, because he doesn't use those broken parameters.

From the precision of the bug reports we got, it seems to me that some of the users facing those issues should be able to sort this out in a clever way. I'd really like to invite them to join in at least for this specific issue. It's easier for people facing the bug since they can test on their own use case.

Both @losintikfos and I think that flask-mongoengine should do the minimum here, leaving the most parameter parsing to either MongoEngine or pymongo. That's pretty much all I can give in terms of direction. From there, any solution that is not a terrible hack should be acceptable.

**Comment by thedrow** [comment] 2016-10-27 08:06
@MongoEngine/flask-mongoengine Do you guys think we have enough maintainers for this repository at the moment?

**Comment by jcass77** [comment] 2016-10-27 12:28
I've created PR #277 which tries to address some of the connection string regressions referred to below. It is probably still a little cumbersome - I tried to change as little as possible in order to test the use case described in #250.

**Comment by lafrech** [comment] 2016-10-27 13:36
@thedrow: Last maintainers are @losintikfos and I, both with few availability, but we manage to keep the bugtracker from exploding. There's not much on the roadmap. The lib does the job. Not much work needed, unless someone wants to introduce something big. (Exception to the rule, current situation is a bit chaotic lately since a change in 0.8 broke a lot of stuff.)

Besides, @wojcikstefan has been pretty active lately and is joining the team.

**Comment by losintikfos** [comment] 2016-10-27 13:40
Sorry guys slightly busy lately but still checking notifications as it comes in now and then - @rozza can you please give @wojcikstefan admin rights please.

Thanks

**Comment by rozza** [comment] 2016-10-31 13:52
@wojcikstefan has admin rights 👍

**Comment by lafrech** [comment] 2016-11-06 21:41
@rozza, I'm not sure he does, does he? And neither do I, BTW. I only have admin rights on Mongoengine, not flask-mongoengine.

There seems to be an issue with Travis that needs admin rights on this repo. See https://github.com/MongoEngine/flask-mongoengine/issues/278.

**Comment by lafrech** [comment] 2016-11-06 22:10
Also, while we're at it, we should ensure that we can manage all the external resources: travis, readthedocs, PyPi, etc.

AFAIU, all CI stuff only requires write access  (or maybe admin rights?) here to modify some git hooks. I don't know about read the docs. I guess it works the same way.

Regarding PyPi, is there anything we need to publish a new version? Or is it just about publishing a new tag here in master branch?

As I said [here](https://github.com/MongoEngine/mongoengine/issues/1342#issuecomment-256633080), I don't intend to take over, but while we're at it, we should ensure that @losintikfos, @wojcikstefan, and maybe myself, have the rights for these and can pass them to future maintainers.

**Comment by rozza** [comment] 2016-11-07 16:36
My apologies - I added you with write permissions. Have updated @lafrech, @wojcikstefan and @losintikfos perms :)

**Comment by lafrech** [comment] 2016-11-30 21:53
v0.8.1 released !

@losintikfos, how shall we proceed for the PyPi release?

On MongoEngine, it is automatic thanks to some Travis tweak.

**Comment by wojcikstefan** [comment] 2016-12-02 16:57
@lafrech @losintikfos @rozza any way we can publish the new release to PyPI? :)

**Comment by losintikfos** [comment] 2016-12-02 17:47
@lafrech if all test passing - please release. 

Thanks

**Comment by lafrech** [comment] 2016-12-02 19:52
@losintikfos all tests pass (except for broken PyPy3 environment) and I did release already: https://github.com/MongoEngine/flask-mongoengine/releases/tag/0.8.1

Just so we know, how has privileges to publish on PyPi? Is it just you or can it be a group? A private key we could share?

**Comment by thedrow** [comment] 2016-12-04 09:29
I have release privileges at least for MongoEngine.

**Comment by wojcikstefan** [comment] 2016-12-04 18:26
@thedrow do you know who has privileges for Flask-MongoEngine? We published a new release 4 days ago, but still haven't been able to upload it to PyPI.

**Comment by thedrow** [comment] 2016-12-05 09:35
I don't know. @rozza Do you have release privileges for Flask-MongoEngine?

**Comment by rozza** [comment] 2016-12-05 10:01
The following have pypi auth:

* anemitz
* the_drow
* losintikfos
* naumanahmad

Who else needs auth?

**Comment by lafrech** [comment] 2016-12-05 10:05
I'd say at least @wojcikstefan. You can add myself as well.

Thanks @rozza!

Do you need anything? A public key?

**Comment by rozza** [comment] 2016-12-05 11:24
I've added @wojcikstefan so he should be good to go. @lafrech if you let him know your pypi username he should be able to add you.

**Comment by lafrech** [comment] 2016-12-05 11:30
Thanks @rozza.

@wojcikstefan I just created a PyPi account (lafrech).

**Comment by lafrech** [comment] 2016-12-05 11:32
It would be nice to reproduce MongoEngine's setup: Travis CI trickery provides automatic PyPi release upon new release in master.

**Comment by wojcikstefan** [comment] 2016-12-05 16:36
> Travis CI trickery provides automatic PyPi release upon new release in master.

@lafrech I'll take care of it in https://github.com/MongoEngine/flask-mongoengine/issues/284

**Closed** 2020-12-26 16:58 UTC
