### ISSUE TITLE
while assigning replicaSet parameter, the replicaSet is gone. This is because of the below code...

### ISSUE THREAD

**Issue by fieliapm** [MongoEngine/flask-mongoengine#251] opened 2016-08-25 06:51 UTC
In master branch, flask_mongoengine/connection.py, line 265:
```
if conn_setting.pop('replicaset', None):
    resolved['replicaSet'] = conn_setting.pop('replicaset', None)
```

 what is f***ing going on lol

Because dict.pop() will return and also remove specific key value pair from dict, so we cannot do dict.pop() twice.
Actually this code should be:
```
replica_set = conn_setting.pop('replicaset', None)
if replica_set:
    resolved['replicaSet'] = replica_set
```

**Comment by losintikfos** [comment] 2016-08-25 07:53
@fieliapm pls are you able to make pull request for this?

Ta!

**Comment by fieliapm** [comment] 2016-08-25 09:42
@losintikfos I just did before, please double check if replicaSet parameter is working. Thanks.

**Comment by lafrech** [comment] 2016-08-25 12:10
Fixed in https://github.com/MongoEngine/flask-mongoengine/pull/253.

Thanks @fieliapm.

**Closed by lafrech** 2016-08-25 12:10 UTC
Labels: bug

**Comment by denny0223** [comment] 2016-11-10 05:56
Hey @losintikfos & @lafrech 

It's seem a critical bug in 0.8.

When use flask 0.11 with flask-mongoengine 0.7.5, there is a lot of ExtDeprecationWarning, but because of this issue our project can not upgrade to 0.8, will any hotfix version release before 0.8.1 or when the 0.8.1 release? Thanks.

**Comment by tzengyuxio** [comment] 2016-11-10 06:51
Same problem here.
It's a dilemma for our running project between staying in 0.7.5 (lots of warning) or upgrading to 0.8.
Could there be any clear release schedule of this hotfix? Thanks.

**Comment by lafrech** [comment] 2016-11-10 08:46
There's been work on the connection code, recently. We're not done, yet, but https://github.com/MongoEngine/flask-mongoengine/commit/d3b737383e932f23ba35dfc1c3e40f7beaf83a9f should have solved a few issues.

Would you like to test latest revision in master and see if it gets any better for you?

If not, you may also want to pay a look at https://github.com/MongoEngine/flask-mongoengine/pull/280, maybe test this version as well, and provide feedback.

Thanks.

**Comment by lafrech** [comment] 2016-11-10 08:49
Sorry, I read a little too fast. This issue is fixed in master and you're asking for a bugfix release.

@wojcikstefan has WIP regarding the connection code. Hopefully, the whole thing should be fixed and relatively stable pretty soon.

**Comment by wojcikstefan** [comment] 2016-11-10 15:11
@tzengyuxio @denny0223 can you confirm the issue is resolved if you use the latest commit on the master branch instead of v0.8? If so, I think we could move with urgency and release a critical bugfix version v0.8.1. My connection/overall code fixes will still take some time as there is a lot of unnecessary complexity to untangle (started working on it in #280).

What do you think about such approach @lafrech ?

**Comment by lafrech** [comment] 2016-11-10 15:28
@wojcikstefan Perfect.

![Approved](http://s2.quickmeme.com/img/34/34dc348757fb77da3c6412990dd96af9f29ac8ae25678a1e7c4d3ca8b8c8aebf.jpg)

**Comment by wojcikstefan** [comment] 2016-11-10 17:34
Great :) @tzengyuxio @denny0223 let us know and we'll move forward with a release if your particular use case is fixed.

**Comment by denny0223** [comment] 2016-11-17 06:15
I had tried current master branch `e300e77` in our beta server and it work great for us :fireworks:
