### ISSUE TITLE
Using mongodb:// style uri's no longer work

### ISSUE THREAD

**Issue by agani** [MongoEngine/flask-mongoengine#247] opened 2016-08-11 18:35 UTC
This [line](https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/connection.py#L276) is the culprit. Was noticed before the release of 0.8 :(

I get a failure: pymongo.errors.ServerSelectionTimeoutError: r2d2_local:27017: [Errno -2] Name or service not known

r2d2_local is the name of my database, not my host.

**Comment by bxy09** [comment] 2016-08-12 08:09
I have found the wrong code

**Comment by lafrech** [comment] 2016-08-22 07:48
Would you like to send a PR?

**Comment by llvtt** [comment] 2016-08-29 22:34
There seem to be a number of things broken with this attempt to parse MongoDB connection strings:

1. "database" becomes "host": https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/connection.py#L274
2. The "replicaset" key may not exist, if the connection is not to a replica set: https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/connection.py#L279 (PyMongo does not fill in "replicaset" to `None` if it doesn't exist).
3. Lack of support for additional options that aren't parsed here, like SSL options.

I'm not sure what the motivation is to parse the connection string like this, but it might be better to push down parsing the connection string entirely to PyMongo or MongoEngine. Alternatively, saving the original connection string along with the parsed options so that it can be pushed down later could also work.

**Comment by lafrech** [comment] 2016-08-30 06:48
Indeed, the more we can leave up to PyMongo or MongoEngine, the better.

Would you like to propose an implementation?

**Comment by losintikfos** [comment] 2016-08-30 07:14
@llvtt do you have a sample test snippet I can use to simulate the issue? I do agree we should overlay the parsing down if possible.

**Comment by llvtt** [comment] 2016-08-30 17:20
@losintikfos To reproduce the issue, we just need to set some options that aren't being saved explicitly by the snippet mentioned. An example would be using the `ssl` option.

    app = Flask(__name__)
    app.config["MONGODB_SETTINGS"] = {
        "db": "test-me",
        # Set the "ssl" option in the connection string.
        "host": "mongodb://localhost:27017/test-me?ssl=true"
    }

    db = MongoEngine(app)

To run MongoDB with SSL, use the following command:

    mongod --sslOnNormalPorts --sslPEMKeyFile server.pem

You can use these certificates to do an easy test: https://github.com/10gen/mongo-orchestration/tree/master/tests/lib. Note that "server.pem" was signed by "ca.pem", so you'll need to concatenate the contents of "ca.pem" to your system-wide CA certificates (use a virtual machine) so that the SSL handshake will succeed.

This SSL issue is the problem I experienced, causing me to comment here. However, it might be simpler to reproduce setting a [write concern option](https://docs.mongodb.com/manual/reference/connection-string/#write-concern-options) in the connection string, since that doesn't require any special files/setup of mongod.

As for an implementation to solve this problem once and for all, I'd have to take a deeper look to understand why we're parsing the URI in the first place. I was investigating this issue on behalf of someone else, so I don't have much experience with this project's code base or even using this project.

**Comment by woosungchu** [comment] 2016-09-14 07:10
**I had the same issue before and I think it has relevant with the wrong virtualenv.** 

In my case, I write the code in the same git repository with multiple envirionment. 
I experienced this same error in my ubuntu laptop but it works fine at my window desktop.

After several trial to figure out this problem,I think when your code written by python3 but virtualenv is python2, you may stuck on this same problem...

**Comment by lokeshmeher** [comment] 2016-09-29 07:56
Faced the same issue:
[stackoverflow link](http://stackoverflow.com/questions/39758077/cannot-connect-to-remote-mongodb-server-using-flask-mongoengine)

**Comment by orarbel** [comment] 2016-09-30 23:18
It seems like using URI the connection settings isn't fetching the correct port but instead uses the default one: https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/connection.py#L272

You can see port isn't fetched

**Comment by chacken** [comment] 2016-10-09 22:22
So is this still being maintained?  This is a pretty big issue to have open for >2 months.

**Comment by lafrech** [comment] 2016-10-10 07:54
Contributors willing to fix the connexion regression in 0.8 are welcome to join in https://github.com/MongoEngine/flask-mongoengine/issues/71#issuecomment-252554167.

**Comment by jacebrowning** [comment] 2016-10-14 20:50
Downgrading to version `0.7.5` fixed the problem for me.

**Comment by wojcikstefan** [comment] 2016-12-12 02:52
This should be fixed in v0.8.1, v0.8.2, and v0.9.0. Thank you for your patience!

**Closed by wojcikstefan** 2016-12-12 02:52 UTC
Labels: bug

**Comment by rajdeepbharati** [comment] 2019-02-09 09:07
I'm facing the same issue

**Comment by lokeshmeher** [comment] 2019-02-11 07:35
@rajdeepbharati Which version are you using? Try upgrading to 0.8.1 or later...

**Comment by anurag-ae** [comment] 2019-09-11 07:12
I am also facing the same issue while connecting to cosmosDB using flask-mongoengine. It requires SSL connection as well as replicaset. Can someone guide me how to connect it?

**Comment by AnimusXCASH** [comment] 2020-01-12 17:33
same here
