### ISSUE TITLE
`Required` to `InputRequired` why?

### ISSUE THREAD

**Issue by Zephor5** [MongoEngine/flask-mongoengine#292] opened 2016-12-21 10:14 UTC
[Use InputRequired validator instead of Required](https://github.com/MongoEngine/flask-mongoengine/commit/c157e34aff11557936a0556ec12eee94c3b635cf#diff-9741519ba30ec3df10dfbd8f06122df8)

I have dups forms in one page, so i have to add num suffix in the name to tell them.
when post the form, i just assign these fields by kwargs.

    _nn = request.form.get('name_%s' % i)
    _xx = request.form.get('xpath_%s' % i)
    _rr = request.form.get('re_%s' % i)
    _ss = request.form.get('specify_%s' % i)
    atf = ArticleFieldForm(csrf_enabled=False, name=_nn, xpath=_xx, re=_rr, specify=_ss)
    article_field_forms.append(atf)

now, I have to add these codes

    atf.name.raw_data = [_nn]
    atf.xpath.raw_data = [_xx]
    atf.re.raw_data = [_rr]
    atf.specify.raw_data = [_ss]

to pass through the validation. :(

**Comment by Zephor5** [comment] 2016-12-22 07:54
I think this should be `DataRequired`

**Comment by wojcikstefan** [comment] 2016-12-22 18:27
Hi @Zephor5! Without diving too deep into this, I see that `InputRequired` was added by PR #197 in response to `Required` being deprecated. Your description contains more information about the workaround you're using rather than the actual problem. Could you elaborate what the issue is, ideally in the form of a failing unit test?

I'd love specifically to see the document structure you're using, the form you create, what data is sent via `request.form`, and what's the validation behavior you expect. The simpler the example, the better.

**Comment by Zephor5** [comment] 2016-12-30 04:15
Actual problem is:

    class ArticleField(BaseDocument):
        task = engine.ReferenceField(Task)
        name = engine.StringField(required=True, max_length=32, verbose_name=u'字段名称')
        xpath = XPathField(verbose_name=u'新闻字段xpath')
        re = RegExpField(verbose_name=u'字段解析正则')
        specify = engine.StringField(max_length=64, verbose_name=u'指定值')

    ArticleFieldForm = model_form(ArticleField, exclude=('task',))

    atf = ArticleFieldForm(csrf_enabled=False, name=_nn, xpath=_xx, re=_rr, specify=_ss)
    atf.validate()

`validate()` return `False` other than `True`

[here](https://github.com/Zephor5/zspider/blob/master/utils/models.py#L57) is the model `ArticleField` and other models.
[here](https://github.com/Zephor5/zspider/blob/master/www/templates/task/add.html) is the html form page to add one task, which is consist of one task form and one task_conf form and many field forms in the backend.
As many field forms in one html form,  `name` attribute of `input` element conflicts, so I set the `name` attribute of each field form to name_0, name_1,.. name_i.

So in the backend I can't just pass the flask request.form to construct the form obj. I have to construct it like I showed before, and it should pass the validate.

**Comment by insspb** [comment] 2022-07-28 02:48
Too outdated to understand a problem. 

Shortly, InputRequired is recommended by WTForms https://wtforms.readthedocs.io/en/3.0.x/validators/#wtforms.validators.DataRequired

in new Flask-Mongoengine, that are preparing to release right now, validators is easy to adjust/extend/overwrite on several levels of prepare. You even able to create own database field with required defaults/behaviour. All extremely documented. So i do not think it is critical problem and closing it

**Closed by insspb** 2022-07-28 02:48 UTC
